// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1aG6YQA061aXT_zcKugLcuwc2mtJ_9yg',
    appId: '1:227274715584:web:8a9dc4526700f99ed11825',
    messagingSenderId: '227274715584',
    projectId: 'surfify-99e91',
    authDomain: 'surfify-99e91.firebaseapp.com',
    databaseURL: 'https://surfify-99e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'surfify-99e91.appspot.com',
    measurementId: 'G-WQM0EY1F2G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo6X9tQtiyduLtvVsTg8Bp2X5vVU634-s',
    appId: '1:227274715584:android:6e9ae81163a0b1c2d11825',
    messagingSenderId: '227274715584',
    projectId: 'surfify-99e91',
    databaseURL: 'https://surfify-99e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'surfify-99e91.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCezo74aAZ38OQb9PWXqWhR0zw5OYeoGQg',
    appId: '1:227274715584:ios:658aead42fbec500d11825',
    messagingSenderId: '227274715584',
    projectId: 'surfify-99e91',
    databaseURL: 'https://surfify-99e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'surfify-99e91.appspot.com',
    iosClientId: '227274715584-d4rm1599mq9b7b1bqrm8cj1n25ofe64q.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMobileFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCezo74aAZ38OQb9PWXqWhR0zw5OYeoGQg',
    appId: '1:227274715584:ios:658aead42fbec500d11825',
    messagingSenderId: '227274715584',
    projectId: 'surfify-99e91',
    databaseURL: 'https://surfify-99e91-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'surfify-99e91.appspot.com',
    iosClientId: '227274715584-d4rm1599mq9b7b1bqrm8cj1n25ofe64q.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectMobileFlutter',
  );
}
